[colors.primary]
background = "#0C0401"
foreground = "#e0def4"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.cursor]
cursor = "#e0def4"
text = "#232323"

[colors.selection]
background = "#403d52"
text = "#e0def4"



[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 200
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[font]
size = 15.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window]
title = "Alacritty"
dynamic_padding = false
opacity = 0.85
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
