[colors.bright]
black = "#6e6a86"
blue = "#c4a7e7"
cyan = "#3e8fb0"
green = "#9ccfd8"
magenta = "#ea9a97"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.cursor]
cursor = "#e0def4"
text = "#191724"

[colors.normal]
black = "#6e6a86"
blue = "#c4a7e7"
cyan = "#3e8fb0"
green = "#9ccfd8"
magenta = "#ea9a97"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.primary]
background = "#070707"
foreground = "#e0def4"

[colors.selection]
background = "#403d52"
text = "#e0def4"

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 200
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15

[font]
size = 14.0

[font.normal]
family = "Iosevka NF Medium"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.90

[window.dimensions]
columns = 130
lines = 30

[window.padding]
x = 10
y = 10

